DROP TABLE IF EXISTS ss_admuser
CREATE TABLE `ss_admuser` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `ADMNAME` varchar(100) NOT NULL,  `ADMPASS` char(50) NOT NULL,  `ADMPERMISSION` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_admuser VALUES('1','admin','21232f297a57a5a743894a0e4a801fc3','1')
DROP TABLE IF EXISTS ss_articles
CREATE TABLE `ss_articles` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `CAT_ID` int(10) unsigned NOT NULL,  `ART_TITLE` varchar(255) NOT NULL,  `ART_TITLE_EN` varchar(255) DEFAULT NULL,  `ART_CONTENT` text NOT NULL,  `ART_CONTENT_EN` text,  `AUTHOR` varchar(255) NOT NULL,  `AUTHOR_EN` varchar(255) DEFAULT NULL,  `SUBMIT_DATE` datetime NOT NULL,  `READCOUNT` int(11) NOT NULL DEFAULT '0',  `IS_SHOW` int(11) NOT NULL DEFAULT '0',  `IS_PUBLIC` int(11) NOT NULL DEFAULT '0',  `IS_HOMESHOW` int(11) NOT NULL DEFAULT '0',  `IS_TOP` int(11) NOT NULL DEFAULT '0',  `IS_DELETE` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=7 DEFAULT CHARSET=utf8
INSERT INTO ss_articles VALUES('1','1','新型建筑扣件的优点','','<p>\r\n	据悉新型建筑扣件的出产不仅符合国家尺度，而且其各项指标大大超越了传统扣件，并在今年召开的全国建筑行业会上予以发布。而且新型扣件被中国建筑金属结构协会建筑扣件委员会评为质量信得过产品。新型扣件有效进步了抗滑、抗破坏和扭转钢度机械机能。经国家建筑工程监视检修中央多次检修，新型扣件抗滑机能合格率达到100%，其机能指标视为免检。扭转钢度和抗破坏等机械机能均符合国家尺度。<br />\r\n<br />\r\n建筑扣件具有实质性特点和显著进步,使扣件减少零件数,减低成本,而且因是自身材料翻边厚度大于空心铆钉厚度,故增加了抗拉强度,抗扭矩刚性大大提高。建筑扣件必须具有足够的强度,耐久性,和一定的弹性,并有效第保持钢轨与轨枕之间的可靠联结.此外,还要求扣件系统零件少,安装简单,便于拆卸。<br />\r\n</p>','','管理员','','2013-07-03 05:27:02','1','0','0','0','0','0')
INSERT INTO ss_articles VALUES('2','1','脚手板搭接铺设过程','','<p>\r\n	作业层脚手板应铺满、铺稳，离开墙面120~150mm;冲压钢脚手板、木脚手板、竹串片脚手板等，应设置在三根横向水平杆上。脚手板对接平铺时，接头处必须设两根横向水平杆，脚手板外伸长应取130~150mm,两块脚手板外伸长度的和不应大于300mm；脚手板搭接铺设时，接头必须支在横向水平杆上，搭接长度应大于200mm,其伸出横向水平杆的长度不应小于100mm。当脚手板长度小于2m时，可采用两根横向水平杆支承，但应将脚手板两端与其可靠固定，严防倾翻。此三种脚手板的铺设可采用对接平铺，亦可采用搭接铺设。<br />\r\n<br />\r\n竹串片脚手板是一种常见的脚手板。竹串片脚手板常用两年12t．生长期的成年毛竹或楠竹劈成宽度不小于50mm的竹片，并采用螺栓穿过并列的竹片拧紧制成，螺栓直径为8-lOmm，间距500～600mm，螺栓孔径不大于lOmm。竹串片脚手板长为2，0—3．Om、宽0．25—0．3m，板厚不小于50mm，见图8-1。竹串片脚手板适用于竹、木和扣件式钢管脚手架，其特点及适用范围与竹笆片脚手板相近，但其强度及周转使用次数略大于竹笆片脚手板。<br />\r\n<br />\r\n脚手板包括水平主体板，分别设置于该主体板前后端的多个钩，分别设置于该主体板前后端的多个槽，设置于每个钩下方以便于自由移入和移出的止动机构，上述前钩与后槽位于相同轴线上，上述后钩与前槽位于相同轴线上。竹笆脚手板应按其主竹筋垂直于纵向水平杆方向铺设，且采用对接平铺，四个角应用直径1.2mm的镀锌钢丝固定在纵向水平杆上。作业层端部脚手板探头长度应取150mm,其板长两端均应与支承杆可靠地固定。<br />\r\n</p>','','管理员','','2013-07-03 05:27:02','4','0','0','0','0','0')
INSERT INTO ss_articles VALUES('3','1','建筑行业的多项规范','','<p>\r\n	建筑施工行业的\"产品固定、人员流动，露天、升降机作业，手工操作、繁重体力劳动，工艺变化大、规则性差，不安全因素变化多端\"等特点，决定了安全生产事故的高发。施工设施和安全防护设施的变化大。按照国家标准《高处作业分级》规定划分，目前建筑施工中有90%以上是高处作业。建筑扣件的固定性和建筑结构的复杂性导致在有限的空间和时间内集中了大量的人力、材料和机械共同施工生产，上下左右多层次的立体交叉作业，造成不安全因素多。建筑施工行业的每一项工程都有一定的工期，从几个月到几年不等，但这个时间是相对短暂的，每一部位的作业也是短暂的。这就容易使管理人员和施工人员产生临时观念，对施工出现的防护设施落实不到位等安全隐患麻痹大意，认为凑合凑合就能过去了，在建筑施工过程中执行和监督职工正确运用安全操作规程，提倡从领导做起，按章行事，避免违章指挥，坚持长期有效、持之以恒地对职工遵章守纪情况实施监督。\r\n</p>','','管理员','','2013-07-03 05:27:02','2','0','0','0','0','0')
INSERT INTO ss_articles VALUES('4','1','步步紧卡具的使用','','<p>\r\n	\"步步紧\"模板卡具的拆除，只需用小锤向卡杆无钩端敲击活动卡头下部，利用振动以及小锤的冲击弹性使之松动，便可摘下卡子。卡具拆除时，应使巧劲，不得用蛮力敲击卡具，防止卡具越敲越紧。完活后把活动卡头顺杆滑向有钩一侧，多个一捆，入库或堆放在指定处盖好，以便下次支模再用。<br />\r\n<br />\r\n步步紧高频加热设备是一种新型建筑用具使用方法快捷，不仅能节省工作时间，提高工作效率，更能节约大量木材，取代了传统的铁丝捆绑法，罗杆丝杠法，固圈加塞法。<br />\r\n<br />\r\n经过使用，我们发现这种卡具的在使用时应注意以下几个问题：<br />\r\n<br />\r\n1、活动卡头一端必须配合木方使用，不得与较硬材料(如钢管等)配合使用，防止卡具不能卡紧。<br />\r\n<br />\r\n2、由于材料的自身局限，\"步步紧\"模板应采用卡具最大有效使用范围为小于80㎝的模板加固。<br />\r\n<br />\r\n3、\"步步紧\"模板卡具支设完毕后，不得在卡具上面踩踏，防止卡具松动引发的安全事故或由于卡具松动造成的胀模。<br />\r\n<br />\r\n4、卡具拆除后，应集中指定地点堆放，并注意防潮处理，防止锈蚀。<br />\r\n<br />\r\n使用时应做好\"步步紧\"保管工作。卡子由于体积小，重量轻，如不做好保管工作，极容易丢失。活动卡头部分容易丢失。钩形卡杆在穿进活动卡头后，应在钩形卡杆尾部用焊条堆焊成一个小鼓包，或穿4㎜孔，拧上螺栓，这样活动卡头就不致脱杆遗失了。\r\n</p>','','管理员','','2013-07-03 05:27:02','2','0','0','0','0','0')
INSERT INTO ss_articles VALUES('5','1','柱模板的构造和安装','','<p>\r\n	模板系统包括模板、支架和紧固件三部分。它是保证混凝土在浇筑过程中保持正确的形状和尺寸，在硬化过程中进行防护和养护的工具。为此，要求模板和支架必须符合下列规定：保证工程结构和构件各部位形状、尺寸和相互位置的正确。具有足够的强度、刚度和稳定性，能可靠地承受新浇混凝土的自重和侧压力，以及在施工过程中所产生的荷载。<br />\r\n<br />\r\n在安装柱模前，应先绑好钢筋，测出标高在钢筋上，同时在已浇筑的基础顶面或楼面上固定好柱模板底部的木框，弹出中心线，根据柱边线及木框竖直模板，并用临时支撑固定。同在一条轴线上的柱，应先校正两头柱模板，再在柱模板上口中心线(或边线)拉一泥水线来校正中间的模板。构造简单，装拆方便，并便于钢筋的绑扎与安装、混凝土的浇筑及养护工艺要求。<br />\r\n<br />\r\n柱模板柱子的断面尺寸不大而比较高。因此，柱模板的构造和安装主要考虑保证垂直度及抵抗新浇混凝土的侧压力。与此同时，也要便于浇筑混凝土、清理垃圾与钢筋绑扎等配合问题。柱子的模板底部应开有清理孔。沿高度方向每隔2米左右开有浇筑孔。柱底部要有钉在底部混凝土上的木框，用来固定柱模板的位置。为承受混凝土的侧压力，拼板外要设柱箍。<br />\r\n</p>','','管理员','','2013-07-03 05:27:02','5','0','0','0','0','0')
INSERT INTO ss_articles VALUES('6','1','建筑扣件的安装与拆除','','建筑扣件的安装与拆除必须按照一定的顺序和工序进行，这样才能有效地防止意外事件的发生，能够按照一定的标准和规范进行.两面三刀根三角立杆应连术水平高的工人担任指挥和监护,负责拆除撤料和监护操作人员的作业.建筑扣件在使用中石油两个扣件对接链接在一起产生重要性能的一组扣件产品,能够按照一定的使用原理和方式进行使用,保证在建筑施工中的良好性能和趋势。无轮架必须搭设双根天轮木组装三角柱式龙门架,每节立柱两端焊法兰盘.拼装三角柱架时,必须检查各部件焊口牢固,各节点螺栓必须紧.井架,龙门架必须设置超高限位\\断绳保险,机械\\手动或边锁定位托杠等安全防护装置.作业区内电线及其他设备有妨碍时,应事先与有关部门联系拆除\\转移或加防护。','','管理员','','2013-07-13 16:16:11','1','0','0','0','0','0')
DROP TABLE IF EXISTS ss_articles_cates
CREATE TABLE `ss_articles_cates` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `FAT_ID` int(10) unsigned NOT NULL,  `CATENAME` varchar(255) NOT NULL,  `CATENAME_EN` varchar(255) DEFAULT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_articles_cates VALUES('1','0','最新动态','')
DROP TABLE IF EXISTS ss_banner
CREATE TABLE `ss_banner` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `IMG_URL` varchar(255) NOT NULL,  `IMG_LINK` varchar(255) DEFAULT NULL,  `IMG_TITLE` varchar(255) DEFAULT NULL,  `IMG_DESC` varchar(255) DEFAULT NULL,  `ORDERNUM` int(10) unsigned NOT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=utf8
INSERT INTO ss_banner VALUES('2','../userupload/banner/1373979258.jpg','','','','1')
INSERT INTO ss_banner VALUES('3','../userupload/banner/1373979268.jpg','','','','2')
INSERT INTO ss_banner VALUES('4','../userupload/banner/1373979276.jpg','','','','3')
DROP TABLE IF EXISTS ss_config
CREATE TABLE `ss_config` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `SITENAME` varchar(200) NOT NULL,  `SITENAME_EN` varchar(200) DEFAULT NULL,  `SITE_TITLE` varchar(200) NOT NULL,  `SITE_TITLE_EN` varchar(200) DEFAULT NULL,  `SITE_DESCRIPTION` text NOT NULL,  `SITE_DESCRIPTION_EN` text,  `SITE_KEYWORDS` text NOT NULL,  `SITE_KEYWORDS_EN` text,  `EMAIL` varchar(255) NOT NULL,  `PHONE` varchar(100) NOT NULL,  `FOX` varchar(100) DEFAULT NULL,  `QQ` varchar(100) DEFAULT NULL,  `MSN` varchar(100) DEFAULT NULL,  `ADDRESS` varchar(255) DEFAULT NULL,  `ADDRESS_EN` varchar(255) DEFAULT NULL,  `LINKMAN` varchar(100) DEFAULT NULL,  `LINKMAN_EN` varchar(100) DEFAULT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_config VALUES('1','南宁市炜坤泰建筑建材','','南宁扣件|南宁脚手架扣件|南宁布料机|南宁市炜坤泰建筑建材','','南宁市炜坤泰建材常年销售建筑扣件、螺栓步步紧、脚手架及配件、门型架、安全网、试模、接头、垫块止水、套筒连接件、滚丝机床、布料机、钢材、筛网等,电话:0317-6760299','','南宁扣件,南宁建筑扣件,南宁建材批发','','info@tysbg.com','0317-6873977,13833707009','0317-6873277','2421118497','','河北省孟村回族自治县宋庄子工业区','','张岳峰','')
DROP TABLE IF EXISTS ss_guest_param
CREATE TABLE `ss_guest_param` (  `IS_MAIL` int(11) NOT NULL DEFAULT '1',  `IS_SHOW` int(11) NOT NULL DEFAULT '0',  `IS_VERICODE` int(11) NOT NULL DEFAULT '0',  `RECEIVE_EMAIL` varchar(255) DEFAULT NULL,  `REPLY_SMTP` varchar(255) DEFAULT NULL,  `REPLY_SMTP_USERNAME` varchar(255) DEFAULT NULL,  `REPLY_SMTP_PASSWORD` varchar(255) DEFAULT NULL) ENGINE=MyISAM DEFAULT CHARSET=utf8
INSERT INTO ss_guest_param VALUES('1','0','0','info@tysbg.com','smtp.163.com','servicelsok','753951')
DROP TABLE IF EXISTS ss_guestbook
CREATE TABLE `ss_guestbook` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `USER_NAME` varchar(255) NOT NULL,  `EMAIL` varchar(255) NOT NULL,  `QQMSN` varchar(255) DEFAULT NULL,  `PHONE` varchar(255) DEFAULT NULL,  `MOBILE` varchar(255) DEFAULT NULL,  `ADDRESS` varchar(255) DEFAULT NULL,  `COMPANY` varchar(255) DEFAULT NULL,  `CON_TITLE` varchar(255) DEFAULT NULL,  `CONTENT` text NOT NULL,  `CONTENT_REPLY` text,  `IS_MAIL` int(11) NOT NULL DEFAULT '1',  `SUBMIT_DATE` datetime NOT NULL,  `REPLY_DATE` datetime NOT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8
DROP TABLE IF EXISTS ss_images
CREATE TABLE `ss_images` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `CAT_ID` int(10) unsigned NOT NULL,  `IMG_NAME` varchar(255) NOT NULL,  `IMG_NAME_EN` varchar(255) DEFAULT NULL,  `IMG_URL` varchar(255) NOT NULL,  `IMG_DESC` text,  `IMG_DESC_EN` text,  `IS_SHOW` int(11) NOT NULL DEFAULT '0',  `IS_HOMESHOW` int(11) NOT NULL DEFAULT '0',  `IS_TOP` int(11) NOT NULL DEFAULT '0',  `IS_DELETE` int(11) NOT NULL DEFAULT '0',  `READCOUNT` int(11) NOT NULL DEFAULT '0',  `SUBMIT_DATE` datetime NOT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=16 DEFAULT CHARSET=utf8
INSERT INTO ss_images VALUES('1','3','荣誉证书','','../userupload/images/1373093321.jpg','','','0','0','0','1','2','2013-07-06 14:48:43')
INSERT INTO ss_images VALUES('2','3','优秀新产品','','../userupload/images/1373093367.jpg','','','0','0','0','1','0','2013-07-06 14:49:28')
INSERT INTO ss_images VALUES('3','3','名牌企业','','../userupload/images/1373093388.jpg','','','0','0','0','1','1','2013-07-06 14:49:49')
INSERT INTO ss_images VALUES('4','2','卷制法兰生产','','../userupload/images/1373093409.jpg','','','0','0','0','1','0','2013-07-06 14:50:10')
INSERT INTO ss_images VALUES('5','3','成品仓库','','../userupload/images/1373093469.jpg','','','0','0','0','1','0','2013-07-06 14:51:12')
INSERT INTO ss_images VALUES('6','3','荣誉证书','','../userupload/images/1373702439.jpg','','','0','0','0','0','2','2013-07-13 16:00:42')
INSERT INTO ss_images VALUES('7','3','荣誉证书','','../userupload/images/1373702474.jpg','','','0','0','0','0','0','2013-07-13 16:01:24')
INSERT INTO ss_images VALUES('8','3','荣誉证书','','../userupload/images/1373702503.jpg','','','0','0','0','0','0','2013-07-13 16:01:51')
INSERT INTO ss_images VALUES('9','3','荣誉证书','','../userupload/images/1373702527.jpg','','','0','0','0','0','0','2013-07-13 16:02:15')
INSERT INTO ss_images VALUES('10','2','化学实验','','../userupload/images/1373702595.gif','','','0','0','0','0','1','2013-07-13 16:03:39')
INSERT INTO ss_images VALUES('11','2','万能实验室','','../userupload/images/1373702677.jpg','','','0','0','0','0','0','2013-07-13 16:04:51')
INSERT INTO ss_images VALUES('12','2','化学实验','','../userupload/images/1373702759.gif','','','0','0','0','0','0','2013-07-13 16:06:14')
INSERT INTO ss_images VALUES('13','2','化学实验','','../userupload/images/1373702792.gif','','','0','0','0','0','0','2013-07-13 16:06:40')
INSERT INTO ss_images VALUES('14','2','物理实验','','../userupload/images/1373702838.gif','','','0','0','0','0','0','2013-07-13 16:07:24')
INSERT INTO ss_images VALUES('15','2','微机配料系统','','../userupload/images/1373702864.gif','','','0','0','0','0','0','2013-07-13 16:07:57')
DROP TABLE IF EXISTS ss_images_cates
CREATE TABLE `ss_images_cates` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `FAT_ID` int(10) unsigned NOT NULL,  `CATENAME` varchar(255) NOT NULL,  `CATENAME_EN` varchar(255) DEFAULT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8
INSERT INTO ss_images_cates VALUES('1','0','资质证书','')
INSERT INTO ss_images_cates VALUES('2','0','生产设备','')
INSERT INTO ss_images_cates VALUES('3','1','宣传海报','')
INSERT INTO ss_images_cates VALUES('4','1','演员照片','')
INSERT INTO ss_images_cates VALUES('5','1','拍摄现场','')
DROP TABLE IF EXISTS ss_link_group
CREATE TABLE `ss_link_group` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `GROUPNAME` varchar(255) NOT NULL,  `TEXT_OR_IMG` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_link_group VALUES('1','首页页脚','0')
DROP TABLE IF EXISTS ss_links
CREATE TABLE `ss_links` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `GROUP_ID` int(10) unsigned NOT NULL,  `LINK_NAME` varchar(255) NOT NULL,  `LINK_TEXT` varchar(255) NOT NULL,  `LINK_URL` varchar(255) NOT NULL,  `LINK_LOGO` varchar(255) NOT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8
INSERT INTO ss_links VALUES('1','1','百度搜索','百度搜索','http://www.baidu.com/','../administrator/images/link_logo.gif')
INSERT INTO ss_links VALUES('2','1','阿里巴巴','阿里巴巴','http://china.alibaba.com/','../administrator/images/link_logo.gif')
INSERT INTO ss_links VALUES('3','1','世界工厂网','世界工厂网','http://ch.gongchang.com/','../administrator/images/link_logo.gif')
INSERT INTO ss_links VALUES('4','1','中国制造网','中国制造网','http://cn.made-in-china.com/','../administrator/images/link_logo.gif')
INSERT INTO ss_links VALUES('5','1','中国建材网','中国建材网','http://www.bmlink.com/','../administrator/images/link_logo.gif')
DROP TABLE IF EXISTS ss_pages
CREATE TABLE `ss_pages` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `FAT_ID` int(10) unsigned NOT NULL,  `PAGE_NAME` varchar(255) NOT NULL,  `PAGE_TITLE` varchar(255) DEFAULT NULL,  `PAGE_TITLE_EN` varchar(255) DEFAULT NULL,  `PAGE_DESCRIPTION` text,  `PAGE_DESCRIPTION_EN` text,  `PAGE_KEYWORDS` text,  `PAGE_KEYWORDS_EN` text,  `PAGE_CONTENT` text,  `PAGE_CONTENT_EN` text,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_pages VALUES('1','0','关于我们','南宁扣件|南宁脚手架扣件|南宁建材批发','','','','','','<p>\r\n	河北省孟村县天源水泵管厂专业生产潜水泵管及相关配件，本厂技术实力雄厚、生产设备先进，可根据客户需求定制多种规格的潜水泵配套钢管，我们生产的水泵管采用优质高频焊管、无缝管、镀锌管和不锈钢管为材质，质量可靠，坚固耐用，具有良好的抗酸碱、耐腐蚀性能。经过多年的生产实践和经验积累，我厂形成了一套完善的生产管理与质量监控体系，确保产品符合国家相关质量标准。<br />\r\n<br />\r\n在产品研发方面，我厂拥有独立的技术部门和经验丰富的产品设计人员，可研制不同流量、不同用途、以及不同水温和介质的潜水电泵、喷泉泵、地热泵等产品，并可承接相关工程的安装和维护。<br />\r\n<br />\r\n另外，我们还生产潜水泵管法兰等配套产品，我们的潜水泵管法兰采用了冲压钢板为原材料，在强度和其它各项性能指标上远远超过铸钢法兰，具有不易脱焊、韧性高等优点。<br />\r\n<br />\r\n本厂的水泵管产品广泛用于农业灌溉、建设施工用水、城乡居民饮用水供应、高原山区人畜用水等领域，多年来，我们始终坚持“质量第一，用户至上”的经营原则，为全国各地广大用户提供了优质的产品和服务，并获得了各界人士的认可与赞誉。天源水泵管全体员工真诚期待与您合作！\r\n</p>','')
DROP TABLE IF EXISTS ss_products
CREATE TABLE `ss_products` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `CAT_ID` int(10) unsigned NOT NULL,  `PRO_NAME` varchar(255) NOT NULL,  `PRO_NAME_EN` varchar(255) DEFAULT NULL,  `PRO_TYPE` varchar(255) DEFAULT NULL,  `PRO_PRICE` decimal(8,2) DEFAULT NULL,  `PRO_IMAGE` varchar(255) NOT NULL,  `PRO_CONTENT` text,  `PRO_CONTENT_EN` text,  `SUBMIT_DATE` datetime NOT NULL,  `READCOUNT` int(11) NOT NULL DEFAULT '0',  `IS_SHOW` int(11) NOT NULL DEFAULT '0',  `IS_HOMESHOW` int(11) NOT NULL DEFAULT '0',  `IS_TOP` int(11) NOT NULL DEFAULT '0',  `IS_DELETE` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=137 DEFAULT CHARSET=utf8
INSERT INTO ss_products VALUES('119','12','直缝焊管','','','0.00','../userupload/product/1376817202.jpg','凡是用钢带生产，在高频焊接设备直缝&nbsp; \r\n焊接的管子都叫直缝焊管。（由于钢管的焊接处成一条直线故而得名）。 \r\n其中按照用途不同，又不同的后道生产工序，.(大致可分为脚手架管，流体管，电线套管，支架管，护栏管等几种） 　　<br />\r\n<br />\r\n而低压流体焊管是直缝焊管的一种，一般用水，煤气的输送， 在焊接完毕后比普通焊管多加以一道水压测试，故而低压流体管比普通直缝焊管价格一般高出一点。','','2013-08-18 17:14:07','1','0','0','0','0')
INSERT INTO ss_products VALUES('120','12','不锈钢管','','','0.00','../userupload/product/1376817274.jpg','薄壁不锈钢管常用在饮用水系统、热水系统等给水系统中，它具有安全可靠、卫生环保、经济适用等优点，已被国内外工程实践证明是给水系统中较好的节能和环保型管材之一。另外，不锈钢管也是一种很有竞争力的给水管材，对改善水质和提高人们生活水平有重要作用。','','2013-08-18 17:18:35','1','0','0','0','0')
INSERT INTO ss_products VALUES('117','12','冷镀锌管','','','0.00','../userupload/product/1376817032.jpg','冷镀锌就是电镀锌，镀锌量很少，只有10－50g/m2，其本身的耐腐蚀性比热镀锌管相差很多。正规的镀锌管生产厂家，为了保证质量，大多不采用电镀锌\r\n（冷镀）。只有那些规模小、设备陈旧的小企业采用电镀锌，当然他们的价格也相对便宜一些。目前建设部已正式下文，淘汰技术落后的冷镀锌管，今后不准用冷镀\r\n锌管作水、煤气管。<br />\r\n<br />\r\n锌层是电镀层，锌层与钢管基体独立分层。锌层较薄，锌层简单附着在钢管基体上，容易脱落。故其耐腐蚀性能差。在新建住宅中，禁止使用冷镀锌钢管作为给水管。','','2013-08-18 17:11:13','6','0','0','0','0')
INSERT INTO ss_products VALUES('118','12','热镀锌管','','','0.00','../userupload/product/1376817144.jpg','热镀锌管是使熔融金属与铁基体反应而产生合金层，从而使基体和镀层二者相结合。热镀锌是先将钢管进行酸洗，为了去除钢管表面的氧化铁，酸洗后，通过氯化铵\r\n或氯化锌水溶液或氯化铵和氯化锌混合水溶液槽中进行清洗，然后送入热浸镀槽中。热镀锌具有镀层均匀，附着力强，使用寿命长等优点。<br />\r\n<br />\r\n常说的镀锌管，镀锌管的用途现在煤气、暖气用的那种铁管也是镀锌管，镀锌管作为水管，使用几年后，管内产生大量锈垢，流出的黄水不仅污染洁具，而且夹\r\n杂着不光滑内壁滋生的细菌，锈蚀造成水中重金属含量过高，严重危害人体的健康。六七十年代，国际上发达国家开始开发新型管材，并陆续禁用镀锌管。中国建设\r\n部等四部委也发文明确从二000年起禁用镀锌管，目前新建小区的冷水管已经很少使用镀锌管了，有些小区的热水管使用的是镀锌管。','','2013-08-18 17:12:46','2','0','0','0','0')
INSERT INTO ss_products VALUES('121','13','潜水泵管','','','0.00','../userupload/product/1376817611.jpg','潜水泵管是一种通用机械，其工作原理是电动机通过泵轴带动叶轮高速旋转，对液体作功，把机械能转换成液体能量，从而把液体输送到目的地。在出水管道的安装方面,需要附设一些必薷的附件及设备,如闸阀、伸缩节、拍门、通气孔等，管道附件因管道长短、扬程高低、铺设方式的不同而不同,应该安装哪些附件由泵站的具体情况而定。','','2013-08-18 17:21:07','3','0','0','1','0')
INSERT INTO ss_products VALUES('122','13','潜水泵管','','','0.00','../userupload/product/1376978625.jpg','潜水泵管是一种通用机械，其工作原理是电动机通过泵轴带动叶轮高速旋转，对液体作功，把机械能转换成液体能量，从而把液体输送到目的地。在出水管道的安装方面,需要附设一些必薷的附件及设备,如闸阀、伸缩节、拍门、通气孔等，管道附件因管道长短、扬程高低、铺设方式的不同而不同,应该安装哪些附件由泵站的具体情况而定。','','2013-08-20 14:02:55','3','0','0','1','0')
INSERT INTO ss_products VALUES('123','13','潜水泵管','','','0.00','../userupload/product/1376978957.jpg','潜水泵管是一种通用机械，其工作原理是电动机通过泵轴带动叶轮高速旋转，对液体作功，把机械能转换成液体能量，从而把液体输送到目的地。在出水管道的安装方面,需要附设一些必薷的附件及设备,如闸阀、伸缩节、拍门、通气孔等，管道附件因管道长短、扬程高低、铺设方式的不同而不同,应该安装哪些附件由泵站的具体情况而定。','','2013-08-20 14:08:14','3','0','0','1','0')
INSERT INTO ss_products VALUES('124','13','潜水泵管','','','0.00','../userupload/product/1376979016.jpg','潜水泵管是一种通用机械，其工作原理是电动机通过泵轴带动叶轮高速旋转，对液体作功，把机械能转换成液体能量，从而把液体输送到目的地。在出水管道的安装方面,需要附设一些必薷的附件及设备,如闸阀、伸缩节、拍门、通气孔等，管道附件因管道长短、扬程高低、铺设方式的不同而不同,应该安装哪些附件由泵站的具体情况而定。','','2013-08-20 14:10:31','1','0','0','1','0')
INSERT INTO ss_products VALUES('125','13','潜水泵管','','','0.00','../userupload/product/1376979081.jpg','潜水泵管是一种通用机械，其工作原理是电动机通过泵轴带动叶轮高速旋转，对液体作功，把机械能转换成液体能量，从而把液体输送到目的地。在出水管道的安装方面,需要附设一些必薷的附件及设备,如闸阀、伸缩节、拍门、通气孔等，管道附件因管道长短、扬程高低、铺设方式的不同而不同,应该安装哪些附件由泵站的具体情况而定。','','2013-08-20 14:11:31','1','0','0','1','0')
INSERT INTO ss_products VALUES('126','13','潜水泵管','','','0.00','../userupload/product/1376979155.jpg','潜水泵管是一种通用机械，其工作原理是电动机通过泵轴带动叶轮高速旋转，对液体作功，把机械能转换成液体能量，从而把液体输送到目的地。在出水管道的安装方面,需要附设一些必薷的附件及设备,如闸阀、伸缩节、拍门、通气孔等，管道附件因管道长短、扬程高低、铺设方式的不同而不同,应该安装哪些附件由泵站的具体情况而定。','','2013-08-20 14:12:44','3','0','0','1','0')
INSERT INTO ss_products VALUES('127','13','潜水泵管','','','0.00','../userupload/product/1376979313.jpg','潜水泵管是一种通用机械，其工作原理是电动机通过泵轴带动叶轮高速旋转，对液体作功，把机械能转换成液体能量，从而把液体输送到目的地。在出水管道的安装方面,需要附设一些必薷的附件及设备,如闸阀、伸缩节、拍门、通气孔等，管道附件因管道长短、扬程高低、铺设方式的不同而不同,应该安装哪些附件由泵站的具体情况而定。','','2013-08-20 14:14:25','3','0','0','1','0')
INSERT INTO ss_products VALUES('128','13','潜水泵管','','','0.00','../userupload/product/1376979392.jpg','潜水泵管是一种通用机械，其工作原理是电动机通过泵轴带动叶轮高速旋转，对液体作功，把机械能转换成液体能量，从而把液体输送到目的地。在出水管道的安装方面,需要附设一些必薷的附件及设备,如闸阀、伸缩节、拍门、通气孔等，管道附件因管道长短、扬程高低、铺设方式的不同而不同,应该安装哪些附件由泵站的具体情况而定。','','2013-08-20 14:16:44','1','0','0','1','0')
INSERT INTO ss_products VALUES('129','14','地下两通','','','0.00','../userupload/product/1376979497.jpg','地下两通是一种可以将2根直管连接起来的管件，在施工中应用非常广泛。','','2013-08-20 14:19:18','1','0','0','0','0')
INSERT INTO ss_products VALUES('130','14','地下截门三通','','','0.00','../userupload/product/1376979590.jpg','地下三通是一种可以将3根直管连接起来的管件，在施工中应用非常广泛。','','2013-08-20 14:20:24','1','0','0','0','0')
INSERT INTO ss_products VALUES('131','14','出水弯头','','','0.00','../userupload/product/1376979709.jpg','','','2013-08-20 14:21:51','1','0','0','0','0')
INSERT INTO ss_products VALUES('132','14','弯头','','','0.00','../userupload/product/1376979753.jpg','弯头是改变管路方向的管件。按角度分，有45°及90°180°三种最常用的，另外根据工程需要还包括60°等其他非正常角度弯头。弯头的材料有铸铁、不锈钢、合金钢、可煅铸铁、碳钢、有色金属及塑料等。<br />\r\n<br />\r\n与管子联结的方式有：直接焊接（最常用的方式）法兰<a href=\"http://www.xyqsbg.com/\"></a>联接、热熔连接、电熔连接、螺纹联接及承插式联接等。按照生产工艺可分为：焊接弯头、冲压弯头、推制弯头、铸造弯头等。其他名称：90度弯头、直角弯、爱而弯等。','','2013-08-20 14:22:35','2','0','0','0','0')
INSERT INTO ss_products VALUES('133','14','管卡','','','0.00','../userupload/product/1376979867.jpg','管卡是水暖安装中常用的一种管件,用于固定管道. 　　<br />\r\n1、材料特性：密度、弯曲强度、冲击韧性、压缩强度、弹性模量、拉伸强度、耐温、颜色。<br />\r\n2、安装程序：装配在焊接板上 装配前，为更好地确定夹的方向，建议先在固定处做好标记，后焊上焊接，嵌上管夹身的下半部分，放上需固定的管子。再放上另一半管夹身和盖板，用螺钉拧紧。 切忌直接焊接已装好管夹的底板。 　　<br />\r\n3、用途：用于地面的固定(注意是地热的地面或者地面有管线的位置不可以打眼固定的)活线都不走石膏线里面.地面找平先的管子也要固定。','','2013-08-20 14:24:28','2','0','0','0','0')
INSERT INTO ss_products VALUES('134','14','井盖','','','0.00','../userupload/product/1376979987.jpg','根据GB/T23858-2009《检查井盖》第4项规定，井盖按照承载能力划分为六个等级： 　　<br />\r\n第一组：（最低选用A15级类型）：绿化带、人行道等禁止机动车辆驶入的区域。 　<br />\r\n第二组：（最低选用B125类型）：人行道、非机动车、小车停车场及地下停车场。 　　<br />\r\n第三组：（最低选用C250类型）：住宅小区、背街小巷、仅有轻型机动车或者小车行驶的区域，道路两边路缘石0.5m内。 　　<br />\r\n第四组：（最低选用D400类型）:城市主干路、公路、高速公路等区域。 　　<br />\r\n第五组：（最低选用E600类型）：货运站、码头、机场等区域。 　　<br />\r\n第六组：（最低选用F900类型）：机场跑道等区域。','','2013-08-20 14:26:29','2','0','0','0','0')
INSERT INTO ss_products VALUES('135','15','法兰','','','0.00','../userupload/product/1376980047.jpg','法兰又叫法兰盘或凸缘盘。法兰是使管子与管子相互连接的零\r\n件，连接于管端。法兰连接或法兰接头，是指由法兰、垫片及螺栓三者相互连接作为一组组合密封结构的可拆连接，管道法兰系指管道装置中配管用的法兰，用在设\r\n备上系指设备的进出口法兰。法兰上有孔眼，螺栓使两法兰紧连。法兰间用衬垫密封。法兰分螺纹连接（丝接）法兰和焊接法兰。<br />','','2013-08-20 14:27:29','2','0','0','0','0')
INSERT INTO ss_products VALUES('136','13','潜水泵管','','','0.00','../userupload/product/1376983222.jpg','潜水泵管是一种通用机械，其工作原理是电动机通过泵轴带动叶轮高速旋转，对液体作功，把机械能转换成液体能量，从而把液体输送到目的地。在出水管道的安装方面,需要附设一些必薷的附件及设备,如闸阀、伸缩节、拍门、通气孔等，管道附件因管道长短、扬程高低、铺设方式的不同而不同,应该安装哪些附件由泵站的具体情况而定。','','2013-08-20 14:30:56','3','0','0','1','0')
DROP TABLE IF EXISTS ss_products_cates
CREATE TABLE `ss_products_cates` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `FAT_ID` int(10) unsigned NOT NULL,  `CATENAME` varchar(255) NOT NULL,  `CATENAME_EN` varchar(255) DEFAULT NULL,  `CATEDESC` text,  `CATEDESC_EN` text,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=16 DEFAULT CHARSET=utf8
INSERT INTO ss_products_cates VALUES('12','0','泵管原材料','','','')
INSERT INTO ss_products_cates VALUES('13','0','潜水泵管','','','')
INSERT INTO ss_products_cates VALUES('14','0','水泵管附件','','','')
INSERT INTO ss_products_cates VALUES('15','0','法兰','','','')
DROP TABLE IF EXISTS ss_qqkefu
CREATE TABLE `ss_qqkefu` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `IS_SHOW` int(11) NOT NULL DEFAULT '0',  `QQ_NUMS` varchar(255) DEFAULT NULL,  `QQ_POSITION` varchar(255) NOT NULL DEFAULT 'right',  `QQ_TOP` int(11) NOT NULL DEFAULT '160',  `QQ_COLOR` varchar(255) NOT NULL DEFAULT 'default_blue',  `QQ_STYLE` int(11) NOT NULL DEFAULT '1',  `QQ_EFFECT` int(10) unsigned NOT NULL DEFAULT '0',  `QQ_OPEN` int(10) unsigned NOT NULL DEFAULT '0',  `KF_TEL` varchar(255) NOT NULL DEFAULT '400-655-8888',  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_qqkefu VALUES('1','0','615912549|售前咨询,402719549|售前咨询,402719549|售后咨询,402719549|技术支持','right','160','default_blue','1','0','0','400-655-8888')
