DROP TABLE IF EXISTS ss_admuser
CREATE TABLE `ss_admuser` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `ADMNAME` varchar(100) NOT NULL,  `ADMPASS` char(50) NOT NULL,  `ADMPERMISSION` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_admuser VALUES('1','admin','21232f297a57a5a743894a0e4a801fc3','1')
DROP TABLE IF EXISTS ss_articles
CREATE TABLE `ss_articles` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `CAT_ID` int(10) unsigned NOT NULL,  `ART_TITLE` varchar(255) NOT NULL,  `ART_TITLE_EN` varchar(255) DEFAULT NULL,  `ART_CONTENT` text NOT NULL,  `ART_CONTENT_EN` text,  `AUTHOR` varchar(255) NOT NULL,  `AUTHOR_EN` varchar(255) DEFAULT NULL,  `SUBMIT_DATE` datetime NOT NULL,  `READCOUNT` int(11) NOT NULL DEFAULT '0',  `IS_SHOW` int(11) NOT NULL DEFAULT '0',  `IS_PUBLIC` int(11) NOT NULL DEFAULT '0',  `IS_HOMESHOW` int(11) NOT NULL DEFAULT '0',  `IS_TOP` int(11) NOT NULL DEFAULT '0',  `IS_DELETE` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8
INSERT INTO ss_articles VALUES('1','1','这是一条测试文章的标题','','<p>这是测试文章的内容</p>','','testdata','','2013-07-03 05:27:02','1','0','0','0','0','0')
INSERT INTO ss_articles VALUES('2','1','这是一条测试文章的标题','','<p>这是测试文章的内容</p>','','testdata','','2013-07-03 05:27:02','1','0','0','0','0','0')
INSERT INTO ss_articles VALUES('3','1','这是一条测试文章的标题','','<p>这是测试文章的内容</p>','','testdata','','2013-07-03 05:27:02','1','0','0','0','0','0')
INSERT INTO ss_articles VALUES('4','1','这是一条测试文章的标题','','<p>这是测试文章的内容</p>','','testdata','','2013-07-03 05:27:02','1','0','0','0','0','0')
INSERT INTO ss_articles VALUES('5','1','这是一条测试文章的标题','','<p>这是测试文章的内容</p>','','testdata','','2013-07-03 05:27:02','4','0','0','0','0','0')
DROP TABLE IF EXISTS ss_articles_cates
CREATE TABLE `ss_articles_cates` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `FAT_ID` int(10) unsigned NOT NULL,  `CATENAME` varchar(255) NOT NULL,  `CATENAME_EN` varchar(255) DEFAULT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_articles_cates VALUES('1','0','最新动态','')
DROP TABLE IF EXISTS ss_banner
CREATE TABLE `ss_banner` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `IMG_URL` varchar(255) NOT NULL,  `IMG_LINK` varchar(255) DEFAULT NULL,  `IMG_TITLE` varchar(255) DEFAULT NULL,  `IMG_DESC` varchar(255) DEFAULT NULL,  `ORDERNUM` int(10) unsigned NOT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_banner VALUES('1','../userupload/banner/1372819890.jpg','','','','1')
DROP TABLE IF EXISTS ss_config
CREATE TABLE `ss_config` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `SITENAME` varchar(200) NOT NULL,  `SITENAME_EN` varchar(200) DEFAULT NULL,  `SITE_TITLE` varchar(200) NOT NULL,  `SITE_TITLE_EN` varchar(200) DEFAULT NULL,  `SITE_DESCRIPTION` text NOT NULL,  `SITE_DESCRIPTION_EN` text,  `SITE_KEYWORDS` text NOT NULL,  `SITE_KEYWORDS_EN` text,  `EMAIL` varchar(255) NOT NULL,  `PHONE` varchar(100) NOT NULL,  `FOX` varchar(100) DEFAULT NULL,  `QQ` varchar(100) DEFAULT NULL,  `MSN` varchar(100) DEFAULT NULL,  `ADDRESS` varchar(255) DEFAULT NULL,  `ADDRESS_EN` varchar(255) DEFAULT NULL,  `LINKMAN` varchar(100) DEFAULT NULL,  `LINKMAN_EN` varchar(100) DEFAULT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_config VALUES('1','南宁市炜坤泰建筑建材','','产品名称|产品名称|公司名称','','这是我的公司或产品简介','','关键词,关键词,关键词','','info@wktjc.com','0771-3818130,0771-5661345,13669608166,18007808185','','1010137165','','南宁市秀安路棕榈湾19栋C11号,南宁市邕宾路24-1号大门右侧1-2号','','唐文','')
DROP TABLE IF EXISTS ss_guest_param
CREATE TABLE `ss_guest_param` (  `IS_MAIL` int(11) NOT NULL DEFAULT '1',  `IS_SHOW` int(11) NOT NULL DEFAULT '0',  `IS_VERICODE` int(11) NOT NULL DEFAULT '0',  `RECEIVE_EMAIL` varchar(255) DEFAULT NULL,  `REPLY_SMTP` varchar(255) DEFAULT NULL,  `REPLY_SMTP_USERNAME` varchar(255) DEFAULT NULL,  `REPLY_SMTP_PASSWORD` varchar(255) DEFAULT NULL) ENGINE=MyISAM DEFAULT CHARSET=utf8
INSERT INTO ss_guest_param VALUES('1','0','0','info@wktjc.com','smtp.163.com','servicelsok','753951')
DROP TABLE IF EXISTS ss_guestbook
CREATE TABLE `ss_guestbook` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `USER_NAME` varchar(255) NOT NULL,  `EMAIL` varchar(255) NOT NULL,  `QQMSN` varchar(255) DEFAULT NULL,  `PHONE` varchar(255) DEFAULT NULL,  `MOBILE` varchar(255) DEFAULT NULL,  `ADDRESS` varchar(255) DEFAULT NULL,  `COMPANY` varchar(255) DEFAULT NULL,  `CON_TITLE` varchar(255) DEFAULT NULL,  `CONTENT` text NOT NULL,  `CONTENT_REPLY` text,  `IS_MAIL` int(11) NOT NULL DEFAULT '1',  `SUBMIT_DATE` datetime NOT NULL,  `REPLY_DATE` datetime NOT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM DEFAULT CHARSET=utf8
DROP TABLE IF EXISTS ss_images
CREATE TABLE `ss_images` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `CAT_ID` int(10) unsigned NOT NULL,  `IMG_NAME` varchar(255) NOT NULL,  `IMG_NAME_EN` varchar(255) DEFAULT NULL,  `IMG_URL` varchar(255) NOT NULL,  `IMG_DESC` text,  `IMG_DESC_EN` text,  `IS_SHOW` int(11) NOT NULL DEFAULT '0',  `IS_HOMESHOW` int(11) NOT NULL DEFAULT '0',  `IS_TOP` int(11) NOT NULL DEFAULT '0',  `IS_DELETE` int(11) NOT NULL DEFAULT '0',  `READCOUNT` int(11) NOT NULL DEFAULT '0',  `SUBMIT_DATE` datetime NOT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8
INSERT INTO ss_images VALUES('1','1','荣誉证书','','../userupload/images/1373093321.jpg','','','0','0','0','0','2','2013-07-06 14:48:43')
INSERT INTO ss_images VALUES('2','1','优秀新产品','','../userupload/images/1373093367.jpg','','','0','0','0','0','0','2013-07-06 14:49:28')
INSERT INTO ss_images VALUES('3','1','名牌企业','','../userupload/images/1373093388.jpg','','','0','0','0','0','1','2013-07-06 14:49:49')
INSERT INTO ss_images VALUES('4','2','卷制法兰生产','','../userupload/images/1373093409.jpg','','','0','0','0','0','0','2013-07-06 14:50:10')
INSERT INTO ss_images VALUES('5','1','成品仓库','','../userupload/images/1373093469.jpg','','','0','0','0','0','0','2013-07-06 14:51:12')
DROP TABLE IF EXISTS ss_images_cates
CREATE TABLE `ss_images_cates` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `FAT_ID` int(10) unsigned NOT NULL,  `CATENAME` varchar(255) NOT NULL,  `CATENAME_EN` varchar(255) DEFAULT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=3 DEFAULT CHARSET=utf8
INSERT INTO ss_images_cates VALUES('1','0','资质证书','')
INSERT INTO ss_images_cates VALUES('2','0','生产设备','')
DROP TABLE IF EXISTS ss_link_group
CREATE TABLE `ss_link_group` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `GROUPNAME` varchar(255) NOT NULL,  `TEXT_OR_IMG` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_link_group VALUES('1','首页页脚','0')
DROP TABLE IF EXISTS ss_links
CREATE TABLE `ss_links` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `GROUP_ID` int(10) unsigned NOT NULL,  `LINK_NAME` varchar(255) NOT NULL,  `LINK_TEXT` varchar(255) NOT NULL,  `LINK_URL` varchar(255) NOT NULL,  `LINK_LOGO` varchar(255) NOT NULL,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=6 DEFAULT CHARSET=utf8
INSERT INTO ss_links VALUES('1','1','百度搜索','百度搜索','http://www.baidu.com/','../administrator/images/link_logo.gif')
INSERT INTO ss_links VALUES('2','1','阿里巴巴','阿里巴巴','http://china.alibaba.com/','../administrator/images/link_logo.gif')
INSERT INTO ss_links VALUES('3','1','世界工厂网','世界工厂网','http://ch.gongchang.com/','../administrator/images/link_logo.gif')
INSERT INTO ss_links VALUES('4','1','中国制造网','中国制造网','http://cn.made-in-china.com/','../administrator/images/link_logo.gif')
INSERT INTO ss_links VALUES('5','1','中国建材网','中国建材网','http://www.bmlink.com/','../administrator/images/link_logo.gif')
DROP TABLE IF EXISTS ss_pages
CREATE TABLE `ss_pages` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `FAT_ID` int(10) unsigned NOT NULL,  `PAGE_NAME` varchar(255) NOT NULL,  `PAGE_TITLE` varchar(255) DEFAULT NULL,  `PAGE_TITLE_EN` varchar(255) DEFAULT NULL,  `PAGE_DESCRIPTION` text,  `PAGE_DESCRIPTION_EN` text,  `PAGE_KEYWORDS` text,  `PAGE_KEYWORDS_EN` text,  `PAGE_CONTENT` text,  `PAGE_CONTENT_EN` text,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_pages VALUES('1','0','关于我们','','','','','','','<p>\r\n	这是公司简介版块，此段文字仅用于演示版面，并非实际网站内容，您可随时登录网站管理后台进行修改，修改方法是，登录网站管理后台，在单页管理栏目中选择公司简介，编辑内容，完成后点击保存按钮。这是公司简介版块，此段文字仅用于演示版面，并非实际网站内容，您可随时登录网站管理后台进行修改，修改方法是，登录网站管理后台，在单页管理栏目中选择公司简介，编辑内容，完成后点击保存按钮。\r\n</p>\r\n<p>\r\n	这是公司简介版块，此段文字仅用于演示版面，并非实际网站内容，您可随时登录网站管理后台进行修改，修改方法是，登录网站管理后台，在单页管理栏目中选择公司简介，编辑内容，完成后点击保存按钮。\r\n</p>','')
DROP TABLE IF EXISTS ss_products
CREATE TABLE `ss_products` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `CAT_ID` int(10) unsigned NOT NULL,  `PRO_NAME` varchar(255) NOT NULL,  `PRO_NAME_EN` varchar(255) DEFAULT NULL,  `PRO_TYPE` varchar(255) DEFAULT NULL,  `PRO_PRICE` decimal(8,2) DEFAULT NULL,  `PRO_IMAGE` varchar(255) NOT NULL,  `PRO_CONTENT` text,  `PRO_CONTENT_EN` text,  `SUBMIT_DATE` datetime NOT NULL,  `READCOUNT` int(11) NOT NULL DEFAULT '0',  `IS_SHOW` int(11) NOT NULL DEFAULT '0',  `IS_HOMESHOW` int(11) NOT NULL DEFAULT '0',  `IS_TOP` int(11) NOT NULL DEFAULT '0',  `IS_DELETE` int(11) NOT NULL DEFAULT '0',  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=84 DEFAULT CHARSET=utf8
INSERT INTO ss_products VALUES('32','1','转向扣件','','','0.00','../userupload/product/1373442914.jpg','<div>\r\n	<p>\r\n		<span>旋转扣件中心是指旋转扣件安装在脚手架架管上的中心位置，主节点是指脚手架管件横杆与竖杆的连接点。剪刀斜杆应用旋转扣件固定在与相交的横向水平杆的伸出端或立杆上，旋转扣件中心线至主节点的距离不宜大于150mm. 一字型、开口型双排脚手架的两端均必须设置横向斜撑，中间宜每隔6跨设置一道。纵向搭接长度不小于1米，并等间距设置3个旋转扣件固定，端部扣件盖板\r\n边缘至搭接纵向水平杆杆端的距离不小于100mm.<br />\r\n<br />\r\n</span> \r\n	</p>\r\n	<p>\r\n		<span>旋转扣件主要用于紧固连接外径为48mm的钢管成直角，任意角度和同一直线。各种扣件材质均可段铸铁。建筑扣件在使用时，应使其内壁弧面与钢管名壁充分接触，然后使用T型螺栓紧固，紧固螺栓的扭力矩应为40N.M。<br />\r\n<br />\r\n</span> \r\n	</p>\r\n	<p>\r\n		<span>旋转扣件比起其他的建筑扣件来具有良好的使用价值，能够在使用中方便使用者，可以在使用中便于使用者进行操作，工作原理比较简单，无须复杂的工序。</span> \r\n	</p>\r\n</div>','','2013-07-10 15:55:36','2','0','0','0','0')
INSERT INTO ss_products VALUES('31','1','十字扣件','','','0.00','../userupload/product/1373442813.jpg','<div>\r\n	<p>\r\n		<span>十字扣件是一种呈十字形的建筑扣件它的生产必须符合按规定程序批准\r\n的图样进行生产。扣件的材料应符合GB9440中KTH330-08牌号规定的力学性能。扣件生产必须按工艺规定的配料比进行配料。扣件热处理严格执行工\r\n艺规定的各阶段的温度和时间。扣件的加工严格按工艺进行，并严格对扣件与钢管的粘合面进行试压整形，以保证扣件抗滑、抗拉性能要求。扣件（除底座外）必须\r\n经过70N.m扭力矩试压检验，不允许破坏。直角扣件的抗滑性能，当P=14KN \r\n时，△2≤0.5mm。对接扣件抗拉性能，当P=6KN时，△2≤0.2mm。砂眼面积大于10平方毫米的砂眼不允许超过一处，且累计面积不得大于40平\r\n方毫米。扣件的粘砂面积累计不得大于100平方毫米。扣件的表面不允许有氧化皮。其余技术要求项目符合GB15831的规定。</span>\r\n	</p>\r\n	<p>\r\n		<span><br />\r\n十字扣件特点：<br />\r\n1、抗变形能力强。与普通的钢板冲压扣件相比，因制作工艺不同，突破了\r\n传统的冲压工艺对材质厚度（冲压工艺只能达到 \r\n3.5毫米的厚度极限,在实际使用过程中因为强度不够而易变形）的限制而达到了5毫米，完全能在保证使用过程中不变形，从而保证了产品的安全和重复有效使\r\n用。直角扣件能够保证扣件在使用中的良好使用性能和用途，保证施工中的正常使用。<br />\r\n<br />\r\n2、抗滑性能强。扣件的抗滑性保证了钢管与扣件呈贴合面状态，贴合面积大，克服了铸铁扣件与钢管呈点或线贴合的缺点，消除了钢管滑脱的隐患。<br />\r\n<br />\r\n3、扣件具有安全优势、质量优势、品牌优势，从事扣件出租省心、省力、租赁收益超过出租低劣铁扣件。<br />\r\n<br />\r\n4、维修方便。因产品本身不易锈蚀、不易破损，使用后维修很方便，既降低了维修难度也节约了维修成本。<br />\r\n<br />\r\n5、抗锈蚀能力强。整件经钝化及镀锌双重防锈蚀处理，其抗锈蚀能力大大提高，使用寿命长，远远超过铸铁扣件的使用寿命。<br />\r\n<br />\r\n6、抗脱能力强。采用新型连接，新型螺帽保证了在钢管有变形的情况下，扣件始终能垂直牢固固定，消除了钢管滑脱的可能。</span>\r\n	</p>\r\n</div>','','2013-07-10 15:54:08','1','0','0','0','0')
INSERT INTO ss_products VALUES('30','1','对接扣件','','','0.00','../userupload/product/1373442586.jpg','<div>\r\n	<p>\r\n		<span>对接扣件是建筑扣件中比较常用的，其优势和特点如下——</span> \r\n	</p>\r\n	<p>\r\n		<span>1、对接扣件具有安全优势、质量优势、品牌优势，这种扣件具有良好的产品优势，能够使在施工时展现出良好的优势。钢管脚手架的出租省心、省力、租赁收益超过出租低劣铁扣件，所以这种脚手架扣件的良好特点在建筑中的使用更加广泛。<br />\r\n<br />\r\n2、对接扣件维修方便。由于扣件本身具有不易锈蚀、不易破损的特点，所以使用后维修很方便，既降低了维修难度也节约了维修成本，减少维修的人力和物力，增加施工的效率和质量。<br />\r\n<br />\r\n3、\r\n对接扣件的抗滑性能强。钢管扣件的抗滑性能保证了钢管与扣件呈贴合面状态，贴合面积大，克服了铸铁扣件与钢管呈点或线贴合的缺点，消除了钢管滑脱的隐患，\r\n保证使用钢管时的安全效果。钢管扣件的抗滑性能比较好的克服了铸铁扣件与钢管呈点或线贴合的缺点，能够有效的减少施工中出现的失误和安全事故。<br />\r\n<br />\r\n4、\r\n对接扣件抗变形能力强。传统冲压工艺只能达到3.5毫米的厚度极限,在实际使用过程中因为强度不够而易变形的限制而达到了5毫米，比传统的冲压工艺的材质\r\n厚度限制大了1.5毫米，完全能保证使用过程中不变形、抗变形，从而保证了产品的安全和重复有效使用。扣件的抗变形能力保证施工时的正常使用，或者频繁的\r\n反复使用，保证了扣件的使用寿命，实现钢管扣件的价值。<br />\r\n<br />\r\n</span> \r\n	</p>\r\n	<p>\r\n		<span>纵向水平杆接长宜采用对接扣件连接，也可采用搭接。对接、搭接应符合下列规定：<br />\r\n纵向水平杆的对接扣件应交错布置：两根两邻纵向水平杆的接头不宜设置在同步或同跨内；不同步或不同跨两个相邻接头在水平方向的距离不应小于500㎜；各接头中心至最近主节点的距离不宜大于纵距的1/3。<br />\r\n若采用搭接时，搭接长度不应小于1m，应等间距设置3个旋转扣件固定，端部扣件盖板边缘至搭接纵向水平杆端的距离不应小于100㎜</span> \r\n	</p>\r\n</div>','','2013-07-10 15:49:53','4','0','0','0','0')
INSERT INTO ss_products VALUES('33','1','转向扣件','','','0.00','../userupload/product/1373443019.jpg','<div>\r\n	<p>\r\n		<span>旋转扣件中心是指旋转扣件安装在脚手架架管上的中心位置，主节点是指脚手架管件横杆与竖杆的连接点。剪刀斜杆应用旋转扣件固定在与相交的横向水平杆的伸出端或立杆上，旋转扣件中心线至主节点的距离不宜大于150mm. 一字型、开口型双排脚手架的两端均必须设置横向斜撑，中间宜每隔6跨设置一道。纵向搭接长度不小于1米，并等间距设置3个旋转扣件固定，端部扣件盖板\r\n边缘至搭接纵向水平杆杆端的距离不小于100mm.<br />\r\n<br />\r\n</span> \r\n	</p>\r\n	<p>\r\n		<span>旋转扣件主要用于紧固连接外径为48mm的钢管成直角，任意角度和同一直线。各种扣件材质均可段铸铁。建筑扣件在使用时，应使其内壁弧面与钢管名壁充分接触，然后使用T型螺栓紧固，紧固螺栓的扭力矩应为40N.M。<br />\r\n<br />\r\n</span> \r\n	</p>\r\n	<p>\r\n		<span>旋转扣件比起其他的建筑扣件来具有良好的使用价值，能够在使用中方便使用者，可以在使用中便于使用者进行操作，工作原理比较简单，无须复杂的工序。</span> \r\n	</p>\r\n</div>','','2013-07-10 15:57:09','1','0','0','0','0')
INSERT INTO ss_products VALUES('34','1','顶托','','','0.00','../userupload/product/1373443182.jpg','<span>可调顶托 用于工程施工，桥梁施工和脚手架碗扣脚手架配合使用。起到上顶，下托的作用！各地叫法不同。规范叫法：可调底座可调顶托 俗称：丝杠 建筑丝杠 油托 U型托 丝杠上节丝杠下节的。</span>','','2013-07-10 15:59:51','3','0','0','0','0')
INSERT INTO ss_products VALUES('35','1','U型卡','','','0.00','../userupload/product/1373527738.jpg','','','2013-07-11 15:32:57','1','0','0','0','0')
INSERT INTO ss_products VALUES('36','1','顶托','','','0.00','../userupload/product/1373528053.jpg','<span>可调顶托 用于工程施工，桥梁施工和脚手架碗扣脚手架配合使用。起到上顶，下托的作用！各地叫法不同。规范叫法：可调底座可调顶托 俗称：丝杠 建筑丝杠 油托 U型托 丝杠上节丝杠下节的。</span>','','2013-07-11 15:34:51','3','0','0','0','0')
INSERT INTO ss_products VALUES('37','1','顶托螺母','','','0.00','../userupload/product/1373528131.jpg','<div>\r\n	<p>\r\n		<span>顶托（顶丝） 用于工程施工的各个领域，适用于桥梁、楼房、涵洞、高速公路等建设，它和脚手架碗扣脚手架配合使用。起到上顶，下托的作用！</span>\r\n	</p>\r\n	<p>\r\n		<span>各地叫法不同：有的叫可调底座、可调顶托 、丝杠、 建筑丝杠、 油托 、U型托 、丝杠上节、丝杠下节、托撑、顶丝等。</span>\r\n	</p>\r\n	<p>\r\n		<span>主要由三部分组成：丝杠、底盘、顶托螺母。</span>\r\n	</p>\r\n	<p>\r\n		<span>丝杠型号多种多样，根据工程需要确定。我们可根据建筑单位需求，生产各种型号的建筑顶托。</span>\r\n	</p>\r\n</div>','','2013-07-11 15:36:00','2','0','0','0','0')
INSERT INTO ss_products VALUES('38','1','顶托配件','','','0.00','../userupload/product/1373528198.jpg','<div>\r\n	<p>\r\n		<span>顶托（顶丝） 用于工程施工的各个领域，适用于桥梁、楼房、涵洞、高速公路等建设，它和脚手架碗扣脚手架配合使用。起到上顶，下托的作用！</span>\r\n	</p>\r\n	<p>\r\n		<span>各地叫法不同：有的叫可调底座、可调顶托 、丝杠、 建筑丝杠、 油托 、U型托 、丝杠上节、丝杠下节、托撑、顶丝等。</span>\r\n	</p>\r\n	<p>\r\n		<span>主要由三部分组成：丝杠、底盘、顶托螺母。</span>\r\n	</p>\r\n	<p>\r\n		<span>丝杠型号多种多样，根据工程需要确定。我们可根据建筑单位需求，生产各种型号的建筑顶托。</span>\r\n	</p>\r\n</div>','','2013-07-11 15:37:29','3','0','0','0','0')
INSERT INTO ss_products VALUES('39','1','顶托上托','','','0.00','../userupload/product/1373528286.jpg','一种顶托，它包括撑杆、托板和夹块，其特征在于：所述撑杆(1)的杆身为螺杆，螺杆可插入建筑上常用的钢管中，螺杆上有一调节螺母(4)：所述托板(2)\r\n为凹槽形，托板四周设有数个U形扣孔(5)，托板与撑杆顶端固定连接，托板顶面上有若干个条状孔(6)，在托板端部开有木板孔(7)，在托板两侧之间固定\r\n有若干个横条(8)，横条上开有若干个钉孔(9)；所述夹块(3)放置在托板上，托板两侧板下端开有U形扣孔(5)，当夹块卡在托板上时，夹块侧板下端的\r\nU形扣孔与托板周边的U形扣孔相对应，在夹块的背面固定有撑板(10)。使用上述结构的顶托支撑梁底模，可节省材料、使用方便、受力合理。','','2013-07-11 15:39:47','3','0','0','0','0')
INSERT INTO ss_products VALUES('40','1','顶托上托下托','','','0.00','../userupload/product/1373528435.jpg','一种顶托，它包括撑杆、托板和夹块，其特征在于：所述撑杆(1)的杆身为螺杆，螺杆可插入建筑上常用的钢管中，螺杆上有一调节螺母(4)：所述托板(2)\r\n为凹槽形，托板四周设有数个U形扣孔(5)，托板与撑杆顶端固定连接，托板顶面上有若干个条状孔(6)，在托板端部开有木板孔(7)，在托板两侧之间固定\r\n有若干个横条(8)，横条上开有若干个钉孔(9)；所述夹块(3)放置在托板上，托板两侧板下端开有U形扣孔(5)，当夹块卡在托板上时，夹块侧板下端的\r\nU形扣孔与托板周边的U形扣孔相对应，在夹块的背面固定有撑板(10)。使用上述结构的顶托支撑梁底模，可节省材料、使用方便、受力合理。','','2013-07-11 15:41:05','2','0','0','0','0')
INSERT INTO ss_products VALUES('41','1','管式顶托','','','0.00','../userupload/product/1373528531.jpg','<div>\r\n	一种顶托，它包括撑杆、托板和夹块，其特征在于：所述撑杆(1)的杆身为螺杆，螺杆可插入建筑上常用的钢管中，螺杆上有一调节螺母(4)：所述托板(2)\r\n为凹槽形，托板四周设有数个U形扣孔(5)，托板与撑杆顶端固定连接，托板顶面上有若干个条状孔(6)，在托板端部开有木板孔(7)，在托板两侧之间固定\r\n有若干个横条(8)，横条上开有若干个钉孔(9)；所述夹块(3)放置在托板上，托板两侧板下端开有U形扣孔(5)，当夹块卡在托板上时，夹块侧板下端的\r\nU形扣孔与托板周边的U形扣孔相对应，在夹块的背面固定有撑板(10)。使用上述结构的顶托支撑梁底模，可节省材料、使用方便、受力合理。\r\n</div>\r\n<h3>\r\n	<br />\r\n</h3>','','2013-07-11 15:42:34','1','0','0','0','0')
INSERT INTO ss_products VALUES('42','2','步步紧','','','0.00','../userupload/product/1373528714.jpg','<span>步步紧是一种新型建筑用具，使用方法快捷，不仅能节省工作时间，提高工作效率，更能节约大量木材，取代了传统的铁丝捆绑法，罗杆丝杠法，固圈加塞法.</span>','','2013-07-11 15:45:38','2','0','0','0','0')
INSERT INTO ss_products VALUES('43','2','粗牙螺杆1','','','0.00','../userupload/product/1373528814.jpg','螺杆是在高温、一定腐蚀、强烈磨损、大扭矩下工作的，因此，螺杆必须：<br />\r\n<br />\r\n1）耐高温，高温下不变形；<br />\r\n2）耐磨损，寿命长；<br />\r\n3）耐腐蚀，物料具有腐蚀性；<br />\r\n4）高强度，可承受大扭矩，高转速；<br />\r\n5）具有良好的切削加工性能；<br />\r\n6）热处理后残余应力小，热变形小等。','','2013-07-11 15:53:02','1','0','0','0','0')
INSERT INTO ss_products VALUES('44','2','粗牙螺杆2','','','0.00','../userupload/product/1373529221.jpg','螺杆是在高温、一定腐蚀、强烈磨损、大扭矩下工作的，因此，螺杆必须：<br />\r\n<br />\r\n1）耐高温，高温下不变形；<br />\r\n2）耐磨损，寿命长；<br />\r\n3）耐腐蚀，物料具有腐蚀性；<br />\r\n4）高强度，可承受大扭矩，高转速；<br />\r\n5）具有良好的切削加工性能；<br />\r\n6）热处理后残余应力小，热变形小等。','','2013-07-11 15:53:57','2','0','0','0','0')
INSERT INTO ss_products VALUES('45','2','钢板模卡','','','0.00','../userupload/product/1373529271.jpg','','','2013-07-11 15:55:44','1','0','0','0','0')
INSERT INTO ss_products VALUES('46','2','高强螺杆','','','0.00','../userupload/product/1373529390.jpg','','','2013-07-11 15:57:04','3','0','0','0','0')
INSERT INTO ss_products VALUES('47','2','蝴蝶扣','','','0.00','../userupload/product/1373529477.jpg','<p>\r\n	<span>蝴蝶卡（蝴蝶扣）是一种新型的建筑器材，是模板拉杆锁紧和锚固的理想工具。它利用夹具楔形插销卡紧拉杆\r\n时产生的阻力将拉杆锚住，工作可靠。与传统螺纹拉杆相比，不仅代替了螺帽、垫片作用，而且改变了传统模板拉杆的操作方式，有效的控制了模板的尺寸，提高了\r\n砼构件表面的平整质量，应用平板扣和蝴蝶扣，具有拉杆无需加工，节省螺纹加工费，拉杆材料可选性大，用钢棍与螺纹钢筋只要能穿过夹具即可(一般\r\n10--12mm拉杆），且拉杆长度不拘，只要够长就行。施工操作十分方便、快捷、比螺纹拉杆节省用工近50%以上，且可反复使用，寿命长，保养费省等优\r\n点！</span>\r\n</p>\r\n<p>\r\n	<span>蝴蝶卡（蝴蝶扣），适用于直径 48钢管作檩，是山型卡的替代产品。</span>\r\n</p>\r\n<p>\r\n	<span>特点：操作方便，快速装卸，能减轻工人劳动强度，加快工程进度百分之五十；坚固耐用，不需保养能反复使用，降低施工成本；负载稳定，安全性高。</span>\r\n</p>\r\n<span>适用范围：直径10mm----12mm圆钢和钢筋节能使用 。</span>','','2013-07-11 15:58:30','1','0','0','0','0')
INSERT INTO ss_products VALUES('48','2','活动卡','','','0.00','../userupload/product/1373529543.jpg','','','2013-07-11 15:59:51','1','0','0','0','0')
INSERT INTO ss_products VALUES('49','2','拉紧器','','','0.00','../userupload/product/1373529624.jpg','<p>\r\n	<span>拉紧器是加固钢模板及压缩木板的器材，主要起拉紧作用。用该器拉紧，再用蝴蝶扣紧固。操作简便，比其他拉紧方法提高校率十倍以上。</span>\r\n</p>\r\n<span>拉紧器是使用在货物的运输、移动、装运或者仓储时固定功能。它们具有锁紧后，不会脱落，安全可靠，轻便、操作简便，保护物体不受损伤。</span>','','2013-07-11 16:00:53','2','0','0','0','0')
INSERT INTO ss_products VALUES('50','2','平板扣','','','0.00','../userupload/product/1373529764.jpg','<span>平板扣是一种新型的建筑器材，是模板拉杆锁紧和锚固的理想工具。它利用夹具楔形插销卡紧拉杆时产生的阻力将拉\r\n杆锚住，工作可靠。与传统螺纹拉杆相比，不仅代替了螺帽、垫片作用，而且改变了传统模板拉杆的操作方式，有效的控制了模板的尺寸，提高了砼构件表面的平整\r\n质量，应用平板扣和蝴蝶扣，具有拉杆无需加工，节省螺纹加工费，拉杆材料可选性大，用钢与螺纹钢筋只要能穿过夹具即可(一般10--12mm拉杆），且拉\r\n杆长度不拘，只要够长就行。施工操作十分方便、快捷、比螺纹拉杆节省用工近50%以上，且可反复使用，寿命长，保养费省等优点。</span>','','2013-07-11 16:03:07','2','0','0','0','0')
INSERT INTO ss_products VALUES('51','2','山型卡','','','0.00','../userupload/product/1373529818.jpg','<span>山型卡，是建筑浇铸紧固模板的器材，规格多样，30斤/袋--65斤/袋。品种齐全，也可订做，200个/袋。因其形状如“山”这型所以叫做山型卡。</span>','','2013-07-11 16:04:00','2','0','0','0','0')
INSERT INTO ss_products VALUES('52','2','山型母','','','0.00','../userupload/product/1373531376.jpg','<span>山型母 又称山型螺母——高强丝杆专用螺母，具有很强的硬度和韧度，球墨精铸铁加工而成。使用方便，可借用郎头或钢筋即可操作，无须借助扳手。山型螺母主要用于工程建筑模板工程施工。</span>','','2013-07-11 16:30:11','1','0','0','0','0')
INSERT INTO ss_products VALUES('53','2','熟铁六角母','','','0.00','../userupload/product/1373531443.jpg','<span>我厂历年来经过多年艰苦创业和生产实践，积累了丰富的经验、使生产工艺先进、检测手段完善、企业产品外型美观、抗拉强度高、机械性能稳定等特点。</span>','','2013-07-11 16:36:48','1','0','0','0','0')
INSERT INTO ss_products VALUES('54','2','细牙螺杆','','','0.00','../userupload/product/1373531840.jpg','','','2013-07-11 16:41:39','1','0','0','0','0')
INSERT INTO ss_products VALUES('55','2','止水螺杆','','','0.00','../userupload/product/1373532140.jpg','在浇筑墙或柱混凝土是固定模板，防止暴模，之所以要止水，就是因为这根杆穿过墙了，水容易沿着螺杆渗透进去，所一止水螺杆在螺杆中间焊接一个四方形的钢筋片 叫止水片，可以防水。','','2013-07-11 16:43:56','6','0','0','0','0')
INSERT INTO ss_products VALUES('56','2','铸铁六角母','','','0.00','../userupload/product/1373532443.jpg','','','2013-07-11 16:48:25','2','0','0','0','0')
INSERT INTO ss_products VALUES('57','3','轮扣式脚手架','','','0.00','../userupload/product/1373533100.jpg','<div>\r\n	<p>\r\n		<span>轮扣式脚手架----建筑界的通用术语，指建筑工地上用在外墙、内\r\n部装修或层高较高无法直接施工的地方。主要为了施工人员上下干活或外围安全网维护及高空安装构件等，说白了就是搭架子，脚手架制作材料通常有：竹、木、钢\r\n管或合成材料等。有些工程也用脚手架当模板使用，此外在广告业、市政、交通路桥、矿山等部门也广泛被使用。</span>\r\n	</p>\r\n	<p>\r\n		<span><br />\r\n<strong><a href=\"http://www.fejzqc.com/\">轮扣脚手架</a></strong>具有可靠的双向自锁能力，解决了传统脚手架靠人工锁紧的不足; 在使用过程中，只需把横杆两端插头插入立杆相应的锥孔中，再敲紧即可，其连接拆卸的快速便利性和搭接质量远远超出了目前使用的<strong>轮扣脚手架</strong>。 搭拆速度是<strong>轮扣脚手架</strong>的8-10倍，是碗扣脚手架的4-5倍。 <strong>轮扣脚手架</strong>无任何活动零件，在结构上只有横杆、立杆两类组成。解决了传统脚手架上活动零件丢失、易损、不易保管的问题，减少了施工单位的经济损失。 <strong>轮扣脚手架</strong>其立杆轴心线与横杆轴心线的垂直交叉精度高，受力性质合理，承载能力是扣件脚手架的4倍，是碗扣脚手架的2倍。<strong>轮扣脚手架</strong>是目前最先进的脚手架支撑体系。 <strong>轮扣脚手架</strong>主架钢管有Q235普碳钢管和低合金高强度钢管两种供选择。 利用过度杆可以与碗扣式脚手架、圆盘式脚手架相互配套使用。 </span>\r\n	</p>\r\n</div>','','2013-07-11 17:02:26','2','0','0','0','0')
INSERT INTO ss_products VALUES('58','3','轮扣式脚手架一角','','','0.00','../userupload/product/1373533452.jpg','','','2013-07-11 17:04:17','1','0','0','0','0')
INSERT INTO ss_products VALUES('59','3','碗扣式脚手架解析图','','','0.00','../userupload/product/1373533525.bmp','','','2013-07-11 17:05:29','1','0','0','0','0')
INSERT INTO ss_products VALUES('60','3','碗扣式脚手架','','','0.00','../userupload/product/1373533584.jpg','碗扣式脚手架是一种新型承插式钢管脚手架。脚手架独创了带齿碗扣接头，具有拼拆迅速、省力，结构稳定可靠，配备完善，通用性强，承载力大，安全可靠，易于加工，不易丢失，便于管理，易于运输，应用广泛等特点，大步提高了工作效率。曾数次获国际及国内的各种嘉奖，是建设部2000年以前十项重点推广新技术之一。<br />\r\n<br />\r\n碗扣型多功能脚手架是在吸取国外同类型脚手架的先进接头和配件工艺的基础上，结合我国实际情况而研制的一种新型脚手架。 碗扣型多功能脚手架接头构造合理，制作工艺简单，作业容易，使用范围广，能充分满足房屋、桥涵、隧道、烟囱、水塔等多种建筑物的施工要求。与其它类型脚手架相比，碗扣型多功能脚手架是一种有广泛发展前景的新型脚手架。','','2013-07-11 17:09:09','1','0','0','0','0')
INSERT INTO ss_products VALUES('61','3','香蕉脚手架','','','0.00','../userupload/product/1373533788.jpg','<p>\r\n	<br />\r\n<strong></strong><br />\r\n<br />\r\n香蕉式脚手架，是目前最普遍的系统脚手架之一，广泛运用于钻油探台、油井、建筑工程等。<br />\r\n<br />\r\n香蕉式脚手架横杆系列 、香蕉式脚手架横梁系列、香蕉式脚手架立杆系列、香蕉式脚手架连接杆系列 、香蕉式脚手架三角架系列、香蕉式脚手架踏板系列、香蕉式脚手架斜撑<br />\r\n<br />\r\n香蕉式脚手架工作高度：3m<br />\r\n<br />\r\n整搭承重：5000kg<br />\r\n<br />\r\n管公称口径：48mm<br />\r\n<br />\r\n轮直径：48mm<br />\r\n<br />\r\n管壁厚：4mm<br />\r\n<br />\r\n管长：3m材料：Q235<br />\r\n<br />\r\n</p>','','2013-07-11 17:14:58','2','0','0','0','0')
INSERT INTO ss_products VALUES('62','3','香蕉脚手架一角','','','0.00','../userupload/product/1373534134.jpg','香蕉式脚手架，是目前最普遍的系统脚手架之一，广泛运用于钻油探台、油井、建筑工程等。<br />\r\n<br />\r\n香蕉式脚手架横杆系列 、香蕉式脚手架横梁系列、香蕉式脚手架立杆系列、香蕉式脚手架连接杆系列 、香蕉式脚手架三角架系列、香蕉式脚手架踏板系列、香蕉式脚手架斜撑<br />\r\n<br />\r\n香蕉式脚手架工作高度：3m<br />\r\n<br />\r\n整搭承重：5000kg<br />\r\n<br />\r\n管公称口径：48mm<br />\r\n<br />\r\n轮直径：48mm<br />\r\n<br />\r\n管壁厚：4mm<br />\r\n<br />\r\n管长：3m材料：Q235<br />','','2013-07-11 17:16:14','1','0','0','0','0')
INSERT INTO ss_products VALUES('63','3','圆盘式脚手架','','','0.00','../userupload/product/1373534201.jpg','圆盘式脚手架是一种新型脚手架，该产品于上世纪八十年代从欧洲引进,是继碗扣式脚手架之后的升级换代产品。又称菊花盘式脚手架系统,插盘式脚手架系统,轮盘式脚手架系统,扣盘式脚手架,layher架( layer架、雷亚架，因为该脚手架的基本原理是由德国LAYHER（雷亚）公司发明，也被业内人士称为“雷亚架”。主要用于大型演唱会的灯光架、背景架。）， 圆盘式多功能脚手架，是继碗扣式脚手架之后的升级换代产品。这种脚手架的插座为直径133mm、厚10mm的圆盘，圆盘上开设8个孔，采用φ48*3.5mm、Q345B钢管做主构件，立杆是在一定长度的钢管上每隔0.60m焊接上一个圆盘，用这种新颖、美观的圆盘连接横杆，底部带连接套。横杆是在钢管两端焊接上带插销的插头制成。 <br />','','2013-07-11 17:19:26','3','0','0','0','0')
INSERT INTO ss_products VALUES('64','3','圆盘式脚手架一角','','','0.00','../userupload/product/1373534417.gif','圆盘式脚手架是一种新型脚手架，该产品于上世纪八十年代从欧洲引进,是继碗扣式脚手架之后的升级换代产品。又称菊花盘式脚手架系统,插盘式脚手架系统,轮\r\n盘式脚手架系统,扣盘式脚手架,layher架( \r\nlayer架、雷亚架，因为该脚手架的基本原理是由德国LAYHER（雷亚）公司发明，也被业内人士称为“雷亚架”。主要用于大型演唱会的灯光架、背景\r\n架。）， \r\n圆盘式多功能脚手架，是继碗扣式脚手架之后的升级换代产品。这种脚手架的插座为直径133mm、厚10mm的圆盘，圆盘上开设8个孔，采用\r\nφ48*3.5mm、Q345B钢管做主构件，立杆是在一定长度的钢管上每隔0.60m焊接上一个圆盘，用这种新颖、美观的圆盘连接横杆，底部带连接套。\r\n横杆是在钢管两端焊接上带插销的插头制成。','','2013-07-11 17:20:40','0','0','0','0','0')
INSERT INTO ss_products VALUES('65','4','J型直跑楼梯段','','','0.00','../userupload/product/1373534698.jpg','','','2013-07-11 17:25:07','1','0','0','0','0')
INSERT INTO ss_products VALUES('66','4','镀锌门型架','','','0.00','../userupload/product/1373534868.jpg','<span>移动脚手架的特点:<br />\r\n移动脚手架由美国首先研制成功，至60年代初，欧洲、日本等国家先后应用并发展这\r\n类脚手架。它具有装拆简单，承载性能好，使用安全可靠等特点，发展速度很快，移动脚手架在各种新型脚手架中，开发最早，使用量也最多，在欧美，日本等国\r\n家，其使用量约占各类脚手架的50%。我国从70年代末开始，先后从日本、美国、英国等国家引进并使用这种脚手架。<br />\r\n移动脚手架主要有主框，横框，\r\n交叉斜撑，脚手板，可调底座等组成。交叉拉杆又称斜拉杆、是纵向连接两副门架的交叉型拉杆。杆件两端压扁部分冲有销孔，组装时与门架立杆上的锁销锁牢。表\r\n面处理：电镀（冷镀锌）、 \r\n浸锌（热镀锌）脚轮：又称为地轮,可安装在移动脚手架下部,组成移动式脚手架.可作为机电安装.油漆粉刷.设备维修.广告制作的活动工作平台.脚轮为6寸\r\n带刹车,具有使用方便.移动灵活.安全可靠等特点.<br />\r\n多种用途<br />\r\n1.用于楼宇、厅堂、桥梁、高架桥、隧道等模板内支顶或作飞模支承主架。<br />\r\n2.作高层建筑的内外排栅脚手架。<br />\r\n3.用于机电安装、船体修造及其它装修工程的活动工作平台。<br />\r\n4.利用移动脚手架配上简易屋架，便可构成临时工地宿舍、仓库或工棚。<br />\r\n5.用于搭设临时的观礼台和看台。<br />\r\n装拆方便<br />\r\n1.普通工人徒手插、套、挂就可以任意进行六种搭设。<br />\r\n2.单件最大重量不超过20公斤，因此提升、装拆和运输及其方便。功效高装拆只需徒手进行，大大提高功效，移动脚手架装拆比扣件钢管架快1/2时间，比竹木脚手架快2/3时间。<br />\r\n安全可靠<br />\r\n1.整体性能好：配有脚踏板、平行架、扣墙管、水平和交叉拉杆管等纵横锁位装置。<br />\r\n2.承受作用力合理：由立管直接垂直承受压力，各性能指标满足施工需要。<br />\r\n3.防火性能好，所有主架和配件均为钢制品。<br />\r\n价廉实用<br />\r\n1.根据用户和国内外资料反映，门式架如保养好，可重复使用30次以上，竹木架是不能比拟的。<br />\r\n2.移动脚手架使用单位面积重量比扣件式钢管架低50%，每次拆耗成本是钢管架的1/2，是竹木架的1/3，工效和效益是显著的，且建筑物越高效益越好。</span>','','2013-07-11 17:27:50','2','0','0','0','0')
INSERT INTO ss_products VALUES('67','4','镀锌爬梯','','','0.00','../userupload/product/1373534950.jpg','','','2013-07-11 17:29:16','1','0','0','0','0')
INSERT INTO ss_products VALUES('68','4','镀锌踏板','','','0.00','../userupload/product/1373534991.jpg','','','2013-07-11 17:29:54','1','0','0','0','0')
INSERT INTO ss_products VALUES('69','4','普通门型架','','','0.00','../userupload/product/1373535021.jpg','<span>移动脚手架的特点:<br />\r\n移动脚手架由美国首先研制成功，至60年代初，欧洲、日本等国家先后应用并发展这\r\n类脚手架。它具有装拆简单，承载性能好，使用安全可靠等特点，发展速度很快，移动脚手架在各种新型脚手架中，开发最早，使用量也最多，在欧美，日本等国\r\n家，其使用量约占各类脚手架的50%。我国从70年代末开始，先后从日本、美国、英国等国家引进并使用这种脚手架。<br />\r\n移动脚手架主要有主框，横框，\r\n交叉斜撑，脚手板，可调底座等组成。交叉拉杆又称斜拉杆、是纵向连接两副门架的交叉型拉杆。杆件两端压扁部分冲有销孔，组装时与门架立杆上的锁销锁牢。表\r\n面处理：电镀（冷镀锌）、 \r\n浸锌（热镀锌）脚轮：又称为地轮,可安装在移动脚手架下部,组成移动式脚手架.可作为机电安装.油漆粉刷.设备维修.广告制作的活动工作平台.脚轮为6寸\r\n带刹车,具有使用方便.移动灵活.安全可靠等特点.<br />\r\n多种用途<br />\r\n1.用于楼宇、厅堂、桥梁、高架桥、隧道等模板内支顶或作飞模支承主架。<br />\r\n2.作高层建筑的内外排栅脚手架。<br />\r\n3.用于机电安装、船体修造及其它装修工程的活动工作平台。<br />\r\n4.利用移动脚手架配上简易屋架，便可构成临时工地宿舍、仓库或工棚。<br />\r\n5.用于搭设临时的观礼台和看台。<br />\r\n装拆方便<br />\r\n1.普通工人徒手插、套、挂就可以任意进行六种搭设。<br />\r\n2.单件最大重量不超过20公斤，因此提升、装拆和运输及其方便。功效高装拆只需徒手进行，大大提高功效，移动脚手架装拆比扣件钢管架快1/2时间，比竹木脚手架快2/3时间。<br />\r\n安全可靠<br />\r\n1.整体性能好：配有脚踏板、平行架、扣墙管、水平和交叉拉杆管等纵横锁位装置。<br />\r\n2.承受作用力合理：由立管直接垂直承受压力，各性能指标满足施工需要。<br />\r\n3.防火性能好，所有主架和配件均为钢制品。<br />\r\n价廉实用<br />\r\n1.根据用户和国内外资料反映，门式架如保养好，可重复使用30次以上，竹木架是不能比拟的。<br />\r\n2.移动脚手架使用单位面积重量比扣件式钢管架低50%，每次拆耗成本是钢管架的1/2，是竹木架的1/3，工效和效益是显著的，且建筑物越高效益越好。</span>','','2013-07-11 17:30:44','1','0','0','0','0')
INSERT INTO ss_products VALUES('70','4','普通爬梯','','','0.00','../userupload/product/1373535073.jpg','','','2013-07-11 17:31:17','1','0','0','0','0')
INSERT INTO ss_products VALUES('71','4','普通踏板','','','0.00','../userupload/product/1373535105.jpg','','','2013-07-11 17:31:48','2','0','0','0','0')
INSERT INTO ss_products VALUES('72','5','安全网','','','0.00','../userupload/product/1373535311.jpg','<span>建筑安全网简介<br />\r\n目前在城市建筑施工中，为了安全及美观起见，均普遍采用安全网，现就本厂生产的安全网作些介绍：<br />\r\n建筑安全网采用聚乙烯生产经精工织造而成。颜色通常为绿色或蓝色，采用丝径为22丝，经纬目数为23*14目，每<br />\r\n平方克重在70克左右。（不含金属扣）幅宽有1米、1.2米、1.3米、1.5米可选。每隔1米有金属扣眼，方便拴绳。<br />\r\n每卷长度通常为20米、30米、50米等。<br />\r\n即国标建筑安全网：1.8m*6m。</span>','','2013-07-11 17:35:44','1','0','0','0','0')
INSERT INTO ss_products VALUES('73','5','脚踏网1','','','0.00','../userupload/product/1373535388.jpg','','','2013-07-11 17:36:32','1','0','0','0','0')
INSERT INTO ss_products VALUES('74','5','脚踏网2','','','0.00','../userupload/product/1373535424.jpg','','','2013-07-11 17:37:06','2','0','0','0','0')
INSERT INTO ss_products VALUES('75','5','平网1','','','0.00','../userupload/product/1373535454.jpg','','','2013-07-11 17:37:37','3','0','0','0','0')
INSERT INTO ss_products VALUES('76','5','平网2','','','0.00','../userupload/product/1373535477.jpg','','','2013-07-11 17:37:59','2','0','0','0','0')
INSERT INTO ss_products VALUES('77','6','钢筋垫块','','','0.00','../userupload/product/1373617882.jpg','','','2013-07-12 16:30:12','2','0','0','0','0')
INSERT INTO ss_products VALUES('78','6','马登','','','0.00','../userupload/product/1373617938.jpg','','','2013-07-12 16:32:20','1','0','0','0','0')
INSERT INTO ss_products VALUES('79','6','水泥垫块','','','0.00','../userupload/product/1373617976.jpg','','','2013-07-12 16:33:07','0','0','0','0','0')
INSERT INTO ss_products VALUES('80','6','水泥垫块','','','0.00','../userupload/product/1373618009.jpg','','','2013-07-12 16:33:40','1','0','0','0','0')
INSERT INTO ss_products VALUES('81','6','水泥垫块','','','0.00','../userupload/product/1373618061.jpg','','','2013-07-12 16:34:30','0','0','0','0','0')
INSERT INTO ss_products VALUES('82','6','水泥垫块','','','0.00','../userupload/product/1373618090.jpg','','','2013-07-12 16:35:00','0','0','0','0','0')
INSERT INTO ss_products VALUES('83','6','止水胶垫','','','0.00','../userupload/product/1373618127.jpg','','','2013-07-12 16:35:31','0','0','0','0','0')
DROP TABLE IF EXISTS ss_products_cates
CREATE TABLE `ss_products_cates` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `FAT_ID` int(10) unsigned NOT NULL,  `CATENAME` varchar(255) NOT NULL,  `CATENAME_EN` varchar(255) DEFAULT NULL,  `CATEDESC` text,  `CATEDESC_EN` text,  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=12 DEFAULT CHARSET=utf8
INSERT INTO ss_products_cates VALUES('1','0','扣件顶托系列','','','')
INSERT INTO ss_products_cates VALUES('2','0','螺杆步步紧系列','','','')
INSERT INTO ss_products_cates VALUES('3','0','脚手架及配件系列','','','')
INSERT INTO ss_products_cates VALUES('4','0','门型架及配件系列','','','')
INSERT INTO ss_products_cates VALUES('5','0','安全网 试模 接头','','','')
INSERT INTO ss_products_cates VALUES('6','0','垫块止水及建筑用品','','','')
INSERT INTO ss_products_cates VALUES('7','0','套筒 连接件 滚丝机床','','','')
INSERT INTO ss_products_cates VALUES('8','0','滚丝机床','','','')
INSERT INTO ss_products_cates VALUES('9','0','布料机吊篮系列','','','')
INSERT INTO ss_products_cates VALUES('10','0','钢材及建筑用品系列','','','')
INSERT INTO ss_products_cates VALUES('11','0','筛网系列','','','')
DROP TABLE IF EXISTS ss_qqkefu
CREATE TABLE `ss_qqkefu` (  `ID` int(10) unsigned NOT NULL AUTO_INCREMENT,  `IS_SHOW` int(11) NOT NULL DEFAULT '0',  `QQ_NUMS` varchar(255) DEFAULT NULL,  `QQ_POSITION` varchar(255) NOT NULL DEFAULT 'right',  `QQ_TOP` int(11) NOT NULL DEFAULT '160',  `QQ_COLOR` varchar(255) NOT NULL DEFAULT 'default_blue',  `QQ_STYLE` int(11) NOT NULL DEFAULT '1',  `QQ_EFFECT` int(10) unsigned NOT NULL DEFAULT '0',  `QQ_OPEN` int(10) unsigned NOT NULL DEFAULT '0',  `KF_TEL` varchar(255) NOT NULL DEFAULT '400-655-8888',  PRIMARY KEY (`ID`)) ENGINE=MyISAM AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
INSERT INTO ss_qqkefu VALUES('1','0','615912549|售前咨询,402719549|售前咨询,402719549|售后咨询,402719549|技术支持','right','160','default_blue','1','0','0','400-655-8888')
